### PR TITLE
Logic changed

### PR DESCRIPTION
**Pull request by Krishjunier**
text editor for basic logic writing #1
 Enhancements to Nanobot Logic Creation:

Interactive Logic Input: Implemented a new interactive multi-line logic entry system for creating nanobots. Users can now input their logic step-by-step, enhancing usability and flexibility.

Command Support: Added support for specific commands during the logic entry process:

edit <line_number>: Users can edit specific lines of their logic by providing the line number, allowing for precise modifications.
delete <line_number>: Users can remove any line of logic by specifying its line number, facilitating easier corrections.
done: Users finalize their input by typing done, which will compile the entered logic into the nanobot's attributes.
Command Instructions: Included a clear set of command instructions displayed at the start of the logic entry phase. This provides users with immediate guidance on how to interact with the logic entry system, improving user experience and reducing errors.

Current Logic Display: Each time a user inputs a command, the current logic is displayed, allowing users to see their progress in real-time and make necessary adjustments without confusion.

Benefits of the Changes:
Enhanced User Experience: The new interactive features allow users to create more complex and tailored logic for their nanobots without needing to restart the entry process.
Increased Flexibility: Users can easily revise their logic, making it more dynamic and user-friendly.
Clear Guidance: Displaying command instructions helps users quickly understand how to use the system effectively, reducing learning time and enhancing productivity.

### CODE REVIEW

**Review by bboonstra — CHANGES_REQUESTED** [review]
This is close to the requested improvement. However, you should not add an edit command, you should let the user use the up and down arrows on the keyboard to change lines. It's unlikely that the solution involves an input() loop.

**Comment by Krishjunier** [comment]
ok sir , i modify code again sir

**Comment by bboonstra** [comment]
Sounds good, update it when you have made the changes!

**Comment by Krishjunier** [comment]
Only output things that occurred when using uptime #29
Sir I fixed this error kindly check it sir

**Comment by bboonstra** [comment]
Closing this because no changes have been made

**Pull request closed without merging**
